services:
  app:
    build:
      context: .
      dockerfile: ./infra/php/Dockerfile
    volumes:
      - ./src:/data

  web:
    build:
      context: .
      dockerfile: ./infra/nginx/Dockerfile
      target: production
    ports:
      - 80:80
    depends_on:
      - app

networks:
  mynetwork: